baseURL = 'https://www.yukonwoodcraft.ca/'
languageCode = 'en-us'
title = 'Yukonwoodcraft - Cabinet making & custom furniture'
theme = 'kraft'

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5
